  Session.set("btnDiv","btn-default");
  Session.set("btn9","btn-default");
  Session.set("btn8","btn-default");
  Session.set("btn7","btn-default");
  Session.set("btnMod","btn-default");
  Session.set("btn6","btn-default");
  Session.set("btn5","btn-default");
  Session.set("btn4","btn-default");
  Session.set("btnMulti","btn-default");
  Session.set("btn3","btn-default");
  Session.set("btn2","btn-default");
  Session.set("btn1","btn-default");
  Session.set("btnSub","btn-default");
  Session.set("btn0","btn-default");
  Session.set("btnCom","btn-default");
  Session.set("btnEqual","btn-default");
  Session.set("btnAdd","btn-default");
  Session.set("btnPower","btn-default");
  Session.set("btnSqr", "btn-default");
  Session.set("btnToBin","btn-default");
  Session.set("result","");
  Session.set("tempAdd","");
  Session.set("btnDel", "btn-default");
  Session.set("btnHistory", "btn-default");
  Session.set("btnOn", "btn-default");
  Session.set("addPushed",false);
  Session.set("subPushed",false);
  Session.set("multiPushed", false);
  Session.set("divPushed", false);
  Session.set("modPushed", false);
  Session.set("powerPushed",false);
  Session.set("sqrPushed",false);
  Session.set("binPushed",false);
  Session.set("equalPushed",false);
